name: Code checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install Python dependencies
        run: pip install flake8
  
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
    
      - name: pytest
        run: |
          pip install -r requirements.txt
          pytest tests/

